# Generated by Django 4.1.9 on 2023-07-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_firebase", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="is_student",
            field=models.BooleanField(default=True),
        ),
    ]
