# Generated by Django 4.1.9 on 2023-07-01 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth_firebase", "0001_initial"),
        ("lessons", "0002_location_canteachat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canteachat",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="canteachat_set",
                to="auth_firebase.profile",
            ),
        ),
        migrations.AlterField(
            model_name="instructorqualification",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instructorqualification_set",
                to="auth_firebase.profile",
            ),
        ),
    ]
