# Generated by Django 4.1.9 on 2023-07-03 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0003_alter_canteachat_instructor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lessons.location",
            ),
        ),
    ]
